zabbix_agent_install_packages:
  - { name: zabbix, enablerepo: zabbix }
  - { name: zabbix-get, enablerepo: zabbix }
  - { name: zabbix-agent, enablerepo: zabbix }

zbx_agent_Pid: "/var/run/zabbix/zabbix_agentd.pid"      # Location of Agent PID File
zbx_agent_Log: "/var/log/zabbix/zabbix_agentd.log"      # Location of Agent Log File
zbx_agent_LogSize: 0                                    # Log File Size In MB ( 0 = disabled Log Rotation )
zbx_agent_Debug: 3                                      # Debug Level (0 = no debug, 1=critical, 2=error info, 3=warnings, 4=debug )
zbx_agent_SourceIp:                                     # Source IP address for outgoing connections.
zbx_agent_Remote: 0                                     # Enable remote commands ( 0=disabled, 1=enabled)
zbx_agent_LogRemote: 0                                  # Log Remote Commands ( Enable logging of executed commands )
zbx_agent_ListenIp:                                     # Agent Listen Ip
zbx_agent_StartAgents: 3                                # Number of Pre-Forked Instances of zabbix_agentd
zbx_agent_HostName:                                     # Put the hostname if not filled in name of the machine is used
zbx_agent_HostMetaItem:                                 # Optional parameter that defines an item used for getting host metadatabx_agent_HostMetaItem: a
zbx_agent_RefreshActiveChecks: 120                      # How often list of active checks is refreshed, in seconds.             
zbx_agent_Buffer: 5                                     # Do not keep data longer then N seconds in buffer.
zbx_agent_BufferSize: 100                               # Maximum number of values in a memory buffer
zbx_agent_MaxLinesSecond: 100                           # Maximum number of new lines the agent will send per second to Zabbix Server

# Advanced Zabbix Agent Parameters
zbx_agent_Timeout: 3                                    # Spend no more than Timeout seconds on processing
zbx_agent_AllowRoot: 1                                  # Allow the agent to run as 'root'
zbx_agent_User: "root"
zbx_agent_Include:                                      # Possible to add multiple lines start always with - like next line.
    - "/etc/zabbix/zabbix_agentd.d/"                    # You may include individual files or all files in a directory in the cfg file.
# USER-DEFINED Zabbix Agent Monitored Parameters
zbx_agent_UnsafeUserParam: 0
zbx_agent_UserParameter: []                             # Add one or more lines with user parameters same as with zbx_agent_Include
zbx_agent_LoadModulePath:                               # Add path of the loadable modules
zbx_agent_Modules: []                                   # Add one or more lines with modules module.so
