- name: restart zabbix-server
  sudo: yes
  service:
    name: zabbix-server
    state: restarted

- name: restart snmpd 
  sudo: yes
  service:
    name: snmpd
    state: restarted

- name: restart snmptrapd
  sudo: yes
  service:
    name: snmptrapd
    state: restarted

- name: restart snmptt
  sudo: yes
  service:
    name: snmptt
    state: restarted

- name: restart httpd
  sudo: yes
  service:
    name: httpd
    state: restarted

- name: reload systemd
  sudo: yes
  command: /usr/bin/systemctl daemon-reload

- name: install g2zproxy
  sudo: yes
  command: /usr/bin/pip install /tmp/configparser-3.3.0r2.tar.gz /tmp/graphite-to-zabbix-0.1.6.tar.gz /tmp/py-zabbix-0.6.1.tar.gz
